module.exports.parseAttestationObject = require("./parseAttestationObject")
module.exports.decode = require("./decode")
module.exports.encode = require("./encode")
module.exports.generateServerMakeCredRequest = require("./generateCreds")
module.exports.generateServerVerificationCreds = require("./generateServerVerificationCred")
module.exports.verifyAssertion = require("./verifyAssertion")
